@echo off
chcp 65001 >nul
echo 正在启动ContestTrace...
echo 1. 运行爬虫...
python run.py --crawl
echo 2. 启动前端服务器...
python -m http.server 8000 --directory contesttrace/frontend
echo 启动完成！请在浏览器中访问 http://localhost:8000
echo 按任意键退出...
pause >nul
