@echo off
chcp 65001 >nul
echo 正在启动ContestTrace...
echo 1. 运行队友的爬虫...
call run_teammate_spiders.bat
echo 2. 执行筛选和汇总...
python run.py --filter-all
echo 3. 启动前端服务器...
python -m http.server 8000 --directory contesttrace/frontend
echo 启动完成！请在浏览器中访问 http://localhost:8000
echo 按任意键退出...
pause >nul
