(function () {
    // Auto-generated by run.bat before frontend startup
    var PUBLIC_API_BASE = "";

    // Allow overriding via localStorage for quick switch
    // localStorage.setItem("ai_rerank_api", "https://xxx.onrender.com/api/ai/rerank")
    var localApi = (window.localStorage && window.localStorage.getItem("ai_rerank_api")) || "";
    if (localApi) {
        window.AI_RERANK_API = localApi;
        return;
    }

    if (PUBLIC_API_BASE) {
        window.AI_RERANK_API = PUBLIC_API_BASE.replace(/\/$/, "") + "/api/ai/rerank";
        return;
    }

    window.AI_RERANK_API = "";
})();
